namespace: eth-node
resources:
- deploy.yaml
- pvc.yaml
- service.yaml
namePrefix: mainnet-
configMapGenerator:
- name: geth-config
  files:
  - config.toml
  options:
    disableNameSuffixHash: true
    labels:
      app: geth
