apiVersion: apps/v1
kind: Deployment
metadata:
  name: geth
  namespace: eth-node
  labels:
    app: geth
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: geth
  template:
    metadata:
      labels:
        app: geth
    spec:
      containers:
      - name: geth
        image: ethereum/client-go:stable
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "4"
            memory: "8Gi"
        volumeMounts:
        - name: config
          mountPath: /etc/geth
        command:
        - "geth"
        - "--config"
        - "/etc/geth/config.toml"
        - "--http"
        - "--ws"
        - "--ipcdisable"
        ports:
        - name: http-rpc
          containerPort: 8545
          protocol: TCP
        - name: ws-rpc
          containerPort: 8546
          protocol: TCP
        - name: dashboard
          containerPort: 8080
          protocol: TCP
        - name: peer
          containerPort: 30303
          protocol: TCP
      volumes:
      - name: config
        configMap:
          name: geth-config
