apiVersion: v1
kind: Service
metadata:
  name: geth
spec:
  selector:
    app: geth
  ports:
  - name: http-rpc
    port: 8545
    targetPort: 8545
    protocol: TCP
  - name: ws-rpc
    port: 8546
    targetPort: 8546
    protocol: TCP
  - name: peer
    port: 30303
    targetPort: 30303
    protocol: TCP
