apiVersion: v1
kind: Service
metadata:
  name: openethereum
spec:
  selector:
    app: openethereum
  ports:
  - name: metrics
    port: 3000
    targetPort: 3000
    protocol: TCP
  - name: jsonrpc
    port: 8545
    targetPort: 8545
    protocol: TCP
  - name: ws
    port: 8546
    targetPort: 8546
    protocol: TCP
  - name: node
    port: 30303
    targetPort: 30303
    protocol: TCP
  - name: discovery
    port: 30303
    targetPort: 30303
    protocol: UDP
